name: goim_api_gateway
server_id: 1
port: 8100
etcd:
  endpoints: ["goim-etcd-01:12379","goim-etcd-02:12381","goim-etcd-03:12383"]
  username:
  password:
  schema: goim
  read_timeout: 5000
  write_timeout: 5000
  dial_timeout: 5000
redis:
  address: ["goim-redis-01:7001","goim-redis-02:7002","goim-redis-03:7003","goim-redis-04:7004"]
  db: 0
  password: goim2023
  prefix: "goim:"
