name: goim_auth_gateway
server_id: 1
etcd:
  endpoints: ["127.0.0.1:2379"]     #  这是etcd集群的节点
  username:
  password:
  schema: goim
  read_timeout: 5000
  write_timeout: 5000
  dial_timeout: 5000
redis:
  address: ["127.0.0.1:6379"]
  db: 0
  password:
  prefix: "goim:"
mysql:
  max_open_conns: 20
  max_idle_conns: 10
  max_lifetime: 120000
  max_idle_time: 7200000
  charset: utf8mb4
  sources:
    - {addr: "127.0.0.1:3306",username: root,password: 123123123,db: goim_user}
#    - {addr: "127.0.0.1:13307",username: root,password: 123123123,db: goim_user}  # 集群
  replicas:
#    - {addr: "127.0.0.1:13308",username: root,password: 123123123,db: goim_user}
#    - {addr: "127.0.0.1:13309",username: root,password: 123123123,db: goim_user}
grpc_server:
  name: goim_auth_server
  server_id: 1
  port: 6600
  max_connection_idle: 0
  max_connection_age: 0
  max_connection_age_grace: 0
  time: 7200000
  timeout: 20000
  connection_limit: 2000
  streams_limit: 2000
  max_recv_msg_size: 4096
  credential:
    cert_file: ./configs/tls/grpc/server.pem
    key_file: ./configs/tls/grpc/server.key
    enabled: true